apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-q4yl
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0002-tenant/tkrw-pr712-0075-0002-app/devfile-sample-q4yl@sha256:2708f0614c4052963aba10c78ac13e37512a738c741e6a45fbfa5f7ea04ace08
        name: my-nodejs
        resources: {}
status: {}
